[workspace]
members = [
 "alice-download",
 "alice-open-data",
 "histogram",
 "root-io",
 "root-ls",
 "malice",
 "examples/simple-analysis",
 "examples/convert_to_json",
 "examples/efficiency_map",
]
