[package]
name = "histogram"
version = "0.1.0"
authors = ["cbourjau <christian.bourjau@cern.ch>"]

[dependencies]
ndarray = {version="^0.11.1", features = ["serde-1"]}
itertools = "^0.6.1"
serde = "1.0.27"
num-traits = "^0.1"
bincode = "1.0.0"
failure = "0.1.1"
