[package]
name = "histogram"
version = "0.1.0"
authors = ["cbourjau <christian.bourjau@cern.ch>"]

[dependencies]
ndarray = {version="^0.10", features = ["serde-1"]} # {path = "../../rust-ndarray"}
itertools = "^0.6.1"
serde = "^1.0"
num-traits = "^0.1"