[package]
name = "alice-sys"
version = "0.1.0"
authors = ["cbourjau <christian.bourjau@cern.ch>"]
build = "build.rs"

[dependencies]
libc = "*"

[build-dependencies]
gcc = "0.3"
bindgen = {git = "https://github.com/servo/rust-bindgen.git"}
