[package]
name = "alice-open-data"
version = "0.1.0"
authors = ["cbourjau <christian.bourjau@cern.ch>"]

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
glob = "^0.2.11"
failure = "0.1.1"
reqwest = "0.8.5"
