[package]
name = "root-io"
version = "0.1.0"
authors = ["cbourjau <christian.bourjau@cern.ch>"]
exclude = ["*test_data/", "*.root"]
description = "Reading of `.root` binary files which are commonly used in particle physics"
repository = "https://github.com/cbourjau/alice-rs"
readme = "README.md"
keywords = ["root", "cern", "alice", "lhc", "physics"]
categories = ["parser-implementations", "science", "data-structures"]
license = "MPL-2.0"


[dependencies]
alice-open-data = { path="../alice-open-data/", version="0.1.0"}
flate2 = "0.2"
xz2 = "^0.1.4"
bitflags = "1.0.0"
quote = "0.3.15"
failure = "0.1.0"

[dependencies.nom]
version = "^3"
#features = ["nightly", "verbose-errors"] # For better error messages