[package]
name = "root-io"
version = "0.1.0"
authors = ["cbourjau <christian.bourjau@cern.ch>"]

[dependencies]
alice-open-data = { path="../alice-open-data/", version="0.1.0"}
flate2 = "0.2"
xz2 = "^0.1.4"
bitflags = "1.0.0"
quote = "0.3.15"
failure = "0.1.0"
clap = "^2"
rustfmt = "0.9.0"

[dependencies.nom]
version = "^3"
#features = ["nightly", "verbose-errors"] # For better error messages